<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['software_updates_additional_updates'] = 'additional updates';
$lang['software_updates_app_description'] = 'Приложение Обновление ПО обеспечивает обновления базовых компонентов операционной системы.';
$lang['software_updates_app_name'] = 'Обновление ПО';
$lang['software_updates_automatic_updates'] = 'Автоматическое обновление';
$lang['software_updates_available_updates'] = 'Доступные обновления';
$lang['software_updates_busy_message'] = 'Другой пользователь или служба в настоящее время используют систему обновлений программного обеспечения. Когда процесс будет завершен, это приложение станет доступно снова.';
$lang['software_updates_current_progress'] = 'Текущий прогресс';
$lang['software_updates_details'] = 'Детали';
$lang['software_updates_install_progress'] = 'Прогресс установки';
$lang['software_updates_loading_updates_message'] = 'Загрузка программного обеспечения обновляет список, будьте терпеливы.';
$lang['software_updates_no_data_available'] = 'Данные отсутствуют.';
$lang['software_updates_overall_progress'] = 'Общий прогресс';
$lang['software_updates_package'] = 'Пакеты';
$lang['software_updates_please_be_patient'] = 'Пожалуйста, будьте терпеливы!';
$lang['software_updates_please_be_patient_detail'] = 'Это может занять минуту или две, чтобы обновить все репозитории и детали обновления. Информация кэшируется для будущего использования.';
$lang['software_updates_progress'] = 'Прогресс';
$lang['software_updates_progress_help'] = 'Ваша система в настоящее время обновляется. Этот процесс может занять некоторое время, поэтому наберитесь терпения!';
$lang['software_updates_recent_software_activity'] = 'Недавнее действие программного обеспечения';
$lang['software_updates_repository'] = 'Репозитории';
$lang['software_updates_return_to_overview'] = 'Вернуться к списку';
$lang['software_updates_software_up_to_date'] = 'Актуальное программное обеспечение';
$lang['software_updates_software_update_in_progress'] = 'Обновление программного обеспечения в процессе. Пожалуйста, зайдите позже.';
$lang['software_updates_software_updates'] = 'Обновление ПО';
$lang['software_updates_software_updates_busy'] = 'Обновление ПО занято';
$lang['software_updates_software_updates_system_busy'] = 'Система обновлений программного обеспечения занята.';
$lang['software_updates_system_is_up_to_date'] = 'Система актуальна.';
$lang['software_updates_the_latest_software_updates_are_installed'] = 'Последние обновления программного обеспечения установлены.';
$lang['software_updates_type'] = 'Тип';
$lang['software_updates_update_all'] = 'Обновить все';
$lang['software_updates_updates'] = 'Обновления';
$lang['software_updates_updates_complete'] = 'Обновление ПО закончено';
$lang['software_updates_upgrade'] = 'Обновление';
$lang['software_updates_wizard_description'] = 'Теперь, когда сеть настроена, критические обновления в основной системе устанавливаются.';
$lang['software_updates_wizard_latest_necessary'] = 'Please update your system software before continuing.';
