<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['software_updates_additional_updates'] = 'additional updates';
$lang['software_updates_app_description'] = 'Aplikacja Aktualizacje Oprogramowania umożliwia aktualizowanie bazowych komponentów systemu operacyjnego.';
$lang['software_updates_app_name'] = 'Aktualizacje Systemowe';
$lang['software_updates_automatic_updates'] = 'Automatyczne aktualizacje';
$lang['software_updates_available_updates'] = 'Dostępne aktualizacje';
$lang['software_updates_busy_message'] = 'Inny użytkownik lub usługa aktualnie korzysta z systemu aktualizacji oprogramowania.  Kiedy proces się zakończy, aplikacja będzie dostępna z powrotem.';
$lang['software_updates_current_progress'] = 'Obecny postęp';
$lang['software_updates_details'] = 'Szczegóły';
$lang['software_updates_install_progress'] = 'Postęp instalacji';
$lang['software_updates_loading_updates_message'] = 'Ładuję listę aktualizacji oprogramowania, proszę o cierpliwość.';
$lang['software_updates_no_data_available'] = 'Brak dostępnych danych.';
$lang['software_updates_overall_progress'] = 'Całkowity postęp';
$lang['software_updates_package'] = 'Paczka';
$lang['software_updates_please_be_patient'] = 'Proszę o cierpliwość!';
$lang['software_updates_please_be_patient_detail'] = 'Może to zająć minutę albo dwie aby uaktualnić wszystkie repozytoria i szczegóły aktualizacji.  Te informacje zostaną zbuforowane do przyszłego użytku.';
$lang['software_updates_progress'] = 'Postęp';
$lang['software_updates_progress_help'] = 'Twój system jest w trakcie aktualizacji.  Proces ten może zająć trochę czasu, prosimy o cierpliwość!';
$lang['software_updates_recent_software_activity'] = 'Ostatnia aktywność oprogramowania';
$lang['software_updates_repository'] = 'Repozytorium';
$lang['software_updates_return_to_overview'] = 'Powrót do Przeglądu';
$lang['software_updates_software_up_to_date'] = 'Oprogramowanie jest aktualne';
$lang['software_updates_software_update_in_progress'] = 'Aktualizacja oprogramowania w toku.  Proszę wrócić później.';
$lang['software_updates_software_updates'] = 'Aktualizacje Oprogramowania';
$lang['software_updates_software_updates_busy'] = 'Aktualizacje Oprogramowania są zajęte';
$lang['software_updates_software_updates_system_busy'] = 'System aktualizacji oprogramowania jest zajęty.';
$lang['software_updates_system_is_up_to_date'] = 'System jest aktualny.';
$lang['software_updates_the_latest_software_updates_are_installed'] = 'Najnowsze aktualizacje oprogramowania są zainstalowane.';
$lang['software_updates_type'] = 'Typ';
$lang['software_updates_update_all'] = 'Uaktualnij wszystko';
$lang['software_updates_updates'] = 'Aktualizacje';
$lang['software_updates_updates_complete'] = 'Zakończone aktualizacje oprogramowania';
$lang['software_updates_upgrade'] = 'Aktualizuj';
$lang['software_updates_wizard_description'] = 'Teraz kiedy Twoja sieć jest już skonfigurowana, krytyczne aktualizacje systemu będą instalowane.';
$lang['software_updates_wizard_latest_necessary'] = 'Proszę uaktualnić swój system przed kontynuacją.';
